name: 'workday_elt'
version: '1.0.0'
config-version: 2
profile: 'snowflake_workday'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  workday_elt:
    refined:
      +schema: REFINED
      +materialized: incremental
    curated:
      +schema: CURATED
      +materialized: table
